version: '3.3'

services:
  prestashop:
    image: bitnami/prestashop:1.7
    environment:
      - PRESTASHOP_FIRST_NAME=${PRESTASHOP_FIRST_NAME}
      - PRESTASHOP_LAST_NAME=${PRESTASHOP_LAST_NAME}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_PASSWORD}
      - PRESTASHOP_HOST=${DNS_DOMAIN_SECURE}
      - PRESTASHOP_EMAIL=${PRESTASHOP_EMAIL}
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY}
      - PRESTASHOP_DATABASE_HOST=mysql
      - PRESTASHOP_DATABASE_NAME=${PRESTASHOP_DATABASE_NAME}
      - PRESTASHOP_DATABASE_USER=${PRESTASHOP_DATABASE_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${PRESTASHOP_DATABASE_PASSWORD}
      - PRESTASHOP_DATABASE_PREFIX=${PRESTASHOP_DATABASE_PREFIX}
      - PRESTASHOP_ENABLE_SSL=1
      - PRESTASHOP_ENABLE_HTTPS=yes
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend_network
      - backend_network
  
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${PRESTASHOP_DATABASE_NAME}
      - MYSQL_USER=${PRESTASHOP_DATABASE_USER}
      - MYSQL_PASSWORD=${PRESTASHOP_DATABASE_PASSWORD}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network
    security_opt:
      - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - frontend_network
      - backend_network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: '${DNS_DOMAIN_SECURE} -> http://prestashop:8080'
      STAGE: 'production' 
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    depends_on:
      - prestashop
    networks:
      - frontend_network

volumes:
  prestashop_data:
  mysql_data:
  ssl_certs_data:

networks:
  frontend_network:
  backend_network: